// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-D6pWzbZ2hzjsyaHNs34iHUJtcGKXwNE',
    appId: '1:724353889734:web:2b22267b134b2c037e2ec7',
    messagingSenderId: '724353889734',
    projectId: 'todoapp-53eae',
    authDomain: 'todoapp-53eae.firebaseapp.com',
    storageBucket: 'todoapp-53eae.firebasestorage.app',
    measurementId: 'G-T5363LHTFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAflJEqImHvlI-cWMeY7FJUe4tERMS-Iy4',
    appId: '1:724353889734:android:ec2ee9f72107fe657e2ec7',
    messagingSenderId: '724353889734',
    projectId: 'todoapp-53eae',
    storageBucket: 'todoapp-53eae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUPBoaekF667NuUYwf1wtM7Hh24bolr4',
    appId: '1:724353889734:ios:0b13fdf91a81a9117e2ec7',
    messagingSenderId: '724353889734',
    projectId: 'todoapp-53eae',
    storageBucket: 'todoapp-53eae.firebasestorage.app',
    iosBundleId: 'com.fatihcoban.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUPBoaekF667NuUYwf1wtM7Hh24bolr4',
    appId: '1:724353889734:ios:0b13fdf91a81a9117e2ec7',
    messagingSenderId: '724353889734',
    projectId: 'todoapp-53eae',
    storageBucket: 'todoapp-53eae.firebasestorage.app',
    iosBundleId: 'com.fatihcoban.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-D6pWzbZ2hzjsyaHNs34iHUJtcGKXwNE',
    appId: '1:724353889734:web:ed0332b1510994f27e2ec7',
    messagingSenderId: '724353889734',
    projectId: 'todoapp-53eae',
    authDomain: 'todoapp-53eae.firebaseapp.com',
    storageBucket: 'todoapp-53eae.firebasestorage.app',
    measurementId: 'G-K27CZFFVD4',
  );

}